server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://awseb-e-3w22asgrrv-stack-awsebrdsdatabase-brswglnpcsns.cnd46u29z8we.eu-north-1.rds.amazonaws.com:3306/ebdb?user=pizzaadmin&password=password
    username: pizzaadmin
    password: password
  flyway:
    url: jdbc:mysql://awseb-e-3w22asgrrv-stack-awsebrdsdatabase-brswglnpcsns.cnd46u29z8we.eu-north-1.rds.amazonaws.com:3306/ebdb?user=pizzaadmin&password=password
    password: password
    user: pizzaadmin
  config:
    activate:
      on-profile: demo
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /