server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://34.65.210.174:3306/PizzaService?user=root&password=password
    username: root
    password: password
  flyway:
    url: jdbc:mysql://34.65.210.174:3306/PizzaService?user=root&password=password
    password: password
    user: root
  config:
    activate:
      on-profile: demo
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /
jwt:
  expiration: 3600000
  secret: mySecret
#server:
#  port: 5000
#spring:
#  datasource:
#    url: jdbc:mysql://awseb-e-3w22asgrrv-stack-awsebrdsdatabase-brswglnpcsns.cnd46u29z8we.eu-north-1.rds.amazonaws.com:3306/ebdb?user=pizzaadmin&password=password
#    username: pizzaadmin
#    password: password
#  flyway:
#    url: jdbc:mysql://awseb-e-3w22asgrrv-stack-awsebrdsdatabase-brswglnpcsns.cnd46u29z8we.eu-north-1.rds.amazonaws.com:3306/ebdb?user=pizzaadmin&password=password
#    password: password
#    user: pizzaadmin
#  config:
#    activate:
#      on-profile: demo
#management:
#  endpoints:
#    web:
#      base-path: /
#      path-mapping:
#        health: /