server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://34.65.210.174:3306/PizzaService?user=root&password=password
    username: root
    password: password
  flyway:
    url: jdbc:mysql://34.65.210.174:3306/PizzaService?user=root&password=password
    password: password
    user: root
  config:
    activate:
      on-profile: demo
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /