insert into pizza (id,
                   title,
                   image,
                   dough_type,
                   size,
                   price,
                   category,
                   popularity)
values (1,
        'Half & Half pizza',
        LOAD_FILE('/Users/juliagaskevich/mysql-toSHARE/pizzas/Half_and_Half_pizza.jpeg'),
        '["Thin", "Traditional"]',
        '[15, 30, 35]',
        666,
        'Grille',
        1);

insert into pizza (id,
                   title,
                   image,
                   dough_type,
                   size,
                   price,
                   category,
                   popularity)
values (2,
        'Cheeseburger Pizza',
        LOAD_FILE('/Users/juliagaskevich/mysql-toSHARE/pizzas/Cheeseburger_Pizza.jpeg'),
        '["Thin", "Traditional"]',
        '[25, 30, 35]',
        400,
        'Vegetarian',
        7);

insert into pizza (id,
                   title,
                   image,
                   dough_type,
                   size,
                   price,
                   category,
                   popularity)
values (3,
        'Cheesy Chicken',
        LOAD_FILE('/Users/juliagaskevich/mysql-toSHARE/pizzas/Cheesy_Chicken.jpg'),
        '["Thin", "Traditional"]',
        '[25, 30, 35]',
        425,
        'Spicy',
        6);
insert into pizza (id,
                   title,
                   image,
                   dough_type,
                   size,
                   price,
                   category,
                   popularity)
values (4,
        'Chicken BBQ',
        LOAD_FILE('/Users/juliagaskevich/mysql-toSHARE/pizzas/Chicken_BBQ.jpg'),
        '["Thin", "Traditional"]',
        '[25, 30, 35]',
        350,
        'Grille',
        4);
insert into pizza (id,
                   title,
                   image,
                   dough_type,
                   size,
                   price,
                   category,
                   popularity)
values (5,
        'Margherita',
        LOAD_FILE('/Users/juliagaskevich/mysql-toSHARE/pizzas/Margherita.jpg'),
        '["Thin", "Traditional"]',
        '[25, 30, 35]',
        405,
        'Vegetarian',
        8);
insert into pizza (id,
                   title,
                   image,
                   dough_type,
                   size,
                   price,
                   category,
                   popularity)
values (6,
        'Meaty BBQ',
        LOAD_FILE('/Users/juliagaskevich/mysql-toSHARE/pizzas/Meaty_BBQ.jpg'),
        '["Thin", "Traditional"]',
        '[25, 30, 35]',
        390,
        'Grille',
        5);
insert into pizza (id,
                   title,
                   image,
                   dough_type,
                   size,
                   price,
                   category,
                   popularity)
values (7,
        'Pepperoni',
        LOAD_FILE('/Users/juliagaskevich/mysql-toSHARE/pizzas/Pepperoni.jpg'),
        '["Thin", "Traditional"]',
        '[25, 30, 35]',
        380,
        'Spicy',
        2);
insert into pizza (id,
                   title,
                   image,
                   dough_type,
                   size,
                   price,
                   category,
                   popularity)
values (8,
        'Super Meaty',
        LOAD_FILE('/Users/juliagaskevich/mysql-toSHARE/pizzas/Meaty_BBQ.jpg'),
        '["Thin", "Traditional"]',
        '[25, 30, 35]',
        430,
        'Spicy',
        10);