insert into pizza (id,
                   title,
                   image,
                   dough_type,
                   size,
                   price,
                   category,
                   popularity)
values (9,
        'Veggie Overload',
        LOAD_FILE('/Users/juliagaskevich/mysql-toSHARE/pizzas/Veggie-Overload.jpg'),
        '["Thin", "Traditional"]',
        '[15, 30, 35]',
        999,
        'Spicy',
        9);

insert into pizza (id,
                   title,
                   image,
                   dough_type,
                   size,
                   price,
                   category,
                   popularity)
values (10,
        'Hawaiian',
        LOAD_FILE('/Users/juliagaskevich/mysql-toSHARE/pizzas/Hawaiian.jpg'),
        '["Thin", "Traditional"]',
        '[25, 30, 35]',
        1010,
        'Spicy',
        7);

insert into pizza (id,
                   title,
                   image,
                   dough_type,
                   size,
                   price,
                   category,
                   popularity)
values (11,
        'Beef Suya',
        LOAD_FILE('/Users/juliagaskevich/mysql-toSHARE/pizzas/Beef-Suya.jpg'),
        '["Thin", "Traditional"]',
        '[25, 30, 35]',
        110,
        'Meat',
        7);
insert into pizza (id,
                   title,
                   image,
                   dough_type,
                   size,
                   price,
                   category,
                   popularity)
values (12,
        'Sweet Chili Chicken',
        LOAD_FILE('/Users/juliagaskevich/mysql-toSHARE/pizzas/Sweet-Chili-Chicken.jpg'),
        '["Thin", "Traditional"]',
        '[25, 30, 35]',
        212,
        'Meat',
        5);